on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  APP_NAME: cli-test
  NAMESPACE: test-app
  CLUSTER_NAME: vipul-rawat
  CLUSTER_PROJECT: kops-deploy
  GAR_PROJECT: kops-deploy
  GAR_REGISTRY: zop-dev

jobs:
  dockerize:
    runs-on: ubuntu-latest
    name: 🐳 Dockerize

    outputs:
      image: ${{ steps.output-image.outputs.image }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: '1.21'
      - name: Get dependencies
        run: |
          go mod download

      - name: Build
        run: |
          CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -buildvcs=false -o main

      - name: Login to GAR
        uses: docker/login-action@v2
        with:
          registry: asia-southeast1-docker.pkg.dev
          username: _json_key
          password: ${{ secrets.CLI_TEST_TEST_APP_DEPLOYMENT_KEY }}

      - name: Build and Push Docker Image to GAR
        uses: docker/build-push-action@v2
        with:
          push: true
          context: .
          file: ./Dockerfile
          tags:
            asia-southeast1-docker.pkg.dev/${{ env.GAR_PROJECT }}/${{ env.GAR_REGISTRY }}/${{ env.APP_NAME }}:${{ github.sha }}
      - id: output-image
        run:
          echo "image=`echo asia-southeast1-docker.pkg.dev/${{ env.GAR_PROJECT }}/${{ env.GAR_REGISTRY }}/${{ env.APP_NAME }}:${{ github.sha }}`" >> "$GITHUB_OUTPUT"

  deployment:
    runs-on: ubuntu-latest
    needs: dockerize
    name: 🚀 Deploy
    env:
      image: ${{ needs.dockerize.outputs.image }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Authorize to GCP service account
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.CLI_TEST_TEST_APP_DEPLOYMENT_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Update Kubectl component
        run: gcloud --quiet components update kubectl

      - name: Set GCloud Project and Fetch Cluster Credentials
        run:
          gcloud container clusters get-credentials ${{ env.CLUSTER_NAME }} --region=asia-southeast1 --project=${{ env.CLUSTER_PROJECT }}

      - name: Update Deployment Image
        run:
          kubectl set image deployment/${{ env.APP_NAME }} ${{ env.APP_NAME }}=${{ env.image }} --namespace ${{ env.NAMESPACE }}
